#!/bin/bash
# Written by Kimmo R. M. Hovi <kimmo@fairwarning.fi>
# Prepare the tarball for rpmbuild. Not needed runtime
# Usage:
# ln -s /path/to/this/dir/privateon-${VERSION}.tar /home/<username>/rpmbuild/SOURCES/
# . prep
# <hack away>
# rpmbuild -ba privateon.spec

VERSION=0.1
rm -rf privateon-${VERSION} privateon-${VERSION}.tar
mkdir privateon-${VERSION}
cp -r install  LICENSE  vpn-default.ini  vpn-gui vpn-monitor privateon-${VERSION}
tar -cf privateon-${VERSION}.tar privateon-${VERSION}
