.\" Manpage for vpn_gui.py.
.\" Contact kimmo@fairwarning.fi or maksim.a.boyko@gmail.com to correct errors or typos.
.TH man 8 "11 Feb 2015" "0.9" "vpn_gui.py man page"
.SH NAME
vpn_gui.py \- VPN GUI
.SH SYNOPSIS
vpn_gui.py
.SH DESCRIPTION
vpn_gui.py is VPN GUI.
.SH OPTIONS
The vpn_gui.py does not take any options.
.SH SEE ALSO
vpn_monitor.py(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Maksim A. Boyko (maksim.a.boyko@gmail.com)
